name: Build

on: [push, pull_request]

jobs:
  coredhcp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.20']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: build coredhcp
        run: |
          set -exu
          cd ./cmds/coredhcp
          go build
  coredhcp-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.20']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: ${{ matrix.go }}
      - name: build coredhcp-generator
        run: |
          set -exu
          cd ./cmds/coredhcp-generator
          go build
          builddir=$(./coredhcp-generator -f core-plugins.txt)
          cd "${builddir}"
          ls -l
          go mod init "coredhcp"
          go mod edit -replace "github.com/insei/coredhcp=./"
          go build
          gofmt -w "${builddir}/coredhcp.go"
          diff -u "${builddir}/coredhcp.go" ./cmds/coredhcp/main.go
