name: Lint

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  checklicenses:
    name: checklicenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check license headers
        run: |
          set -exu
          go get -u github.com/u-root/u-root/tools/checklicenses
          $(go env GOPATH)/bin/checklicenses -c .ci/checklicenses_config.json
