name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.20']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: run unit tests
        run: |
          go get -v -t ./...
          echo "" > coverage.txt
          for d in $(go list ./...); do
              go test -v -race -coverprofile=profile.out -covermode=atomic "${d}"
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
          done
      - name: report coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt
          flags: unittests
          fail_ci_if_error: true
          verbose: true
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.20']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: setup integ tests
        run: |
          ./.ci/setup-integ.sh
      - name: run integ tests
        run: |
          cd integ
          go get -v -t -tags=integration ./...
          echo "" > coverage.txt
          for d in $(go list -tags=integration ./...); do
              go test -c -tags=integration -v -race -coverprofile=profile.out -covermode=atomic "${d}"
              testbin="./$(basename $d).test"
              # only run it if it was built - i.e. if there are integ tests
              test -x "${testbin}" && sudo "./${testbin}"
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
          done
      - name: report coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          files: integ/coverage.txt
          flags: integtests
          fail_ci_if_error: true
          verbose: true
